### ISSUE TITLE
CATALOG.XML has invalid defaultLocale

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Test-Datasets#13]
DatasetDiscoveryMetadata for 101AA00DS0003.000 (and several other datasets) has an invalid encoding of defaultLocale:
![image](https://user-images.githubusercontent.com/62906211/211913100-5faa9f31-5d8b-47a5-bfd4-da53214bdf06.png)

Here is a valid encoding from earlier in the file:
![image](https://user-images.githubusercontent.com/62906211/211913264-2b31ec9a-eaaa-491e-a902-c9cc937df1be.png)

**Comment by kusala9** [comment]
see #14 , similar comment. I can delete these - not sure they're useful anyway....

**Comment by DavidGrant-NIWC** [comment]
The issue with these in particular is that they don't conform to the schema, and therefore we can't deserialize the XC.

In general, defaultLocale is only useful if the default is other than "eng" (which isn't allowed).

**Comment by kusala9** [comment]
close. caused by out of date data being used to create exchange sets. Not required for ECDIS. Re-raise in S-164 repository if required.
