### ISSUE TITLE
CATALOG.XML defaultLocale has invalid S100_MD_LanguageCode

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Test-Datasets#14]
Valid language codes are listed here: https://schemas.s100dev.net/schemas/S100/5.0.0/resources/Codelists/cat/codelists.html

Note that "EN", "ENG", and "ENGLISH" are all invalid. Instead, "eng" should be used, or the defaultLocale should be omitted:
![image](https://user-images.githubusercontent.com/62906211/211914382-61e82868-933a-4a43-828c-2fc0c38dc6d8.png)

**Comment by kusala9** [comment]
these are hangovers from edition 4.0.0 in the original metadata (I migrated/converted the ed4 metadata to produce the ed5 exchange set). In 4.0.0 defaultLocale was mandatory so all 4.0.0 CATALOG.XML's include this (with possibly erroneous fields). I think we should delete these from the edition5.0.0 CATALOG.XML as they're not mandatory fields and their use in an ECDIS is currently unclear to me...

**Comment by kusala9** [comment]
close. this is no longer an issue in the S-164 datasets. Caused by migration of edition 4.0.0 data into early exchange sets.
