### ISSUE TITLE
CATALOG.XML protectionScheme present with dataProtection = false

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Test-Datasets#16]
datasetDiscoveryMetadata.protectionScheme is an optional field. It should not be present when dataProtection is set to false.

**Comment by kusala9** [comment]
agree. Will modify CATALOG.XML accordingly.

**Comment by kusala9** [comment]
done for version 2.0. Actually, as this is an optional field it's not a problem if it's there for unencrypted data is it? The boolean flag asserts whether something is encrypted, this one just holds a name of an encryption scheme. Suggest this is actually not that useful at all really.... :-)

**Comment by DavidGrant-NIWC** [comment]
There are many unnecessary fields like this. I agree, the presence or absence of _protectionScheme_ should be sufficient to determine if the data is encrypted. I also agree that the original encoding is not wrong, it just looks odd and could indicate a user error where the boolean flag is set to the incorrect value.

**Comment by kusala9** [comment]
close this one. I believe the exchange sets produced in the S-164 repo will only use this field when cells are encrypted. If it persists it can be re-raised in the S-164 repo.
