### ISSUE TITLE
CATALOG.xml using unexpected mrn identifiers

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Test-Datasets#20]
For 101AA00DS0021.000 datasetID is `urn:mrn:iho:101AA00DS0021:1`, which does not conform to an expected mrn format (`urn:mrn:iho:pub:*` expected). The entry for 101AA00DS0022.00 has the same issue.

For other datasets the datasetID prefix contains `urn:mrn:iho:cksum:sha256` which does not conform to the expected format (`urn:mrn:iho:hash:sha256`)

![image](https://user-images.githubusercontent.com/62906211/212421091-a11bbb3f-c606-4488-95de-d41098a53a2b.png)

![image](https://user-images.githubusercontent.com/62906211/212419528-b55b2edc-d77d-484a-9aa2-161ab9ee6d0e.png)

**Comment by kusala9** [comment]
fixed in IHO_V12 exchange set posted.

**Comment by kusala9** [comment]
close this one. I believe it's fixed in latest exchange sets. Any further issues should be raised in the S-164 repository.
