### ISSUE TITLE
Move S-164 data to S-164 repo

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Test-Datasets#23]
Move the S-164 data from here to https://github.com/iho-ohi/S-164-Sub-Group

**Comment by kusala9** [comment]
agreed at S-164 SubWG. Will wait until current batch of cells are conformant with v1.1.0 of FC though....

**Comment by kusala9** [comment]
suggest this repo is an S-101 "staging area" and data is pulled from here to S-164 for construction of exchange sets only. further, propose that folder names are changed to avoid confusion between this repository and the activities in the S-164 repo?

**Comment by TomRichardson6** [comment]
As @kusala9 has said this Repo will continue to exist for S-101 TDS development and when adequately mature and needed cells will be migrated to the S-164 repo and packaged as Exchange Sets there. We may have developmental cells that aren't included in S-164 etc
