### ISSUE TITLE
Validate S-64 test datasets against feature catalogue revisions

### ISSUE THREAD

**Issue by kusala9** [iho-ohi/S-101-Test-Datasets#3]
The S-64 test datasets were created with an older version of the feature catalogue, which was compiled as the 1.0.0 FC with all the associations correctly defined. We should re-validate against latest/updated FC and establish how many changes need to be made to get the datasets conformant.

**Comment by TomRichardson6** [comment]
@kusala9 I have been validating these cells in 7Cs Analyzer I think that should identify any FC compliance issues although the tool continues to evolve. I will keep this open to remind us that this validation needs to be done on cells once included in S-164 content.

**Comment by TomRichardson6** [comment]
Closing this issue as validation using the relevant feature catalogues is now part of the TDS production process.
