### ISSUE TITLE
S-164-1.1.0/PowerUp/V0 : Nautical Information without information

### ISSUE THREAD

**Issue by plebihan29n** [iho-ohi/S-101-Test-Datasets#41]
The mandatory complex attribute "information" is not defined when the Nautical Information concerns a pictorial representation

**Comment by DavidGrant-NIWC** [comment]
Consider raising a DCEG issue to remodel `NauticalInformation` so that `pictorialRepresentation` is part of `information`. It seems odd that an `information` complex attribute is required when it has no contents.

**Comment by TomRichardson6** [comment]
Closed now that DCEG issue has been raised. TDS action to follow any DCEG change.
