### ISSUE TITLE
cells/101AA00DS0006/3/101AA00DS0006.000 won't load on ECDIS

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Test-Datasets#46]
The `dataCoverage` min/max scales are reversed, which causes the S-101 loading algorithm to never select the dataset.
![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/62906211/2aa9e4dd-c66e-4a15-b060-ebf5f8955501)

**Comment by TomRichardson6** [comment]
Edition 4 of this cell has now been uploaded to resolve this.
