### ISSUE TITLE
Naming convention for datasets

### ISSUE THREAD

**Issue by kusala9** [iho-ohi/S-101-Test-Datasets#49]
The current datasets still have the usage band embedded in the name. Do we need this? S-164 dispensed with the usage code, e.g. uses 101AA00DBASE.000 instead of 101AA005DBASE.000

The numeric codes are spurious. If they stay in the names then we'll need to edit the S-164 draft to put the usage bands in again.

**Comment by RichardCoyles** [comment]
I think that embedding the S-57 usage code in the S-101 dataset name is a useful reference in areas of dual fuel - but in S-164 it should be removed. IMO

**Comment by plebihan29n** [comment]
I understand that  to end with "5DBASE" the dataset file name is conform but in order to not introduce confusion you propose to not introduce the S57 original intended usage code in the name . And this will be true for all test datasets.
Correct ?

**Comment by plebihan29n** [comment]
Dear Tom,
I have done the change of name before to see that you labelled "for 1.2.0 Update" , is it disturbing to deliver the next version with new names ? 
Pol

**Comment by plebihan29n** [comment]
This proposal has been encoded the delivered version 3 of S-164

**Comment by TomRichardson6** [comment]
Closed as now resolved
