### ISSUE TITLE
Change request for 101AA00DS0004.000

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Test-Datasets#50]
The S-101 PSWG has asked me to request that the surface geometry representing `LocalMagneticAnomaly` be increased in size so that it's representative of actual use. At the current size when the dataset is displayed at scale (1:22k) the centered point symbol is not visible (it's offset beyond the boundary of the features geometry).

PSWG issue: https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/214#issuecomment-1664395612

Portrayal of current encoding:
![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/62906211/b0148249-3933-4588-a6e2-4996ec2e7ec9)

**Comment by TomRichardson6** [comment]
Updated dataset has been provided, issue closed.

**Comment by DavidGrant-NIWC** [comment]
https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/214#issuecomment-1706361015
![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/62906211/f83e7f83-cc40-476e-880c-5d795c0a30b5)
