### ISSUE TITLE
Remove zip files

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Test-Datasets#54]
Repo should not contain zip files - provide distributions via the release/tag mechanism or create a branch. Recommend delete the zip file from dev/cells:

![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/62906211/4a09c935-6dad-4514-8064-3e87d4398d3b)

**Comment by TomRichardson6** [comment]
This ZIP file has now been deleted.
