### ISSUE TITLE
S-164_1.1/V1/LightVisibilty = obscured under LightSectored

### ISSUE THREAD

**Issue by plebihan29n** [iho-ohi/S-101-Test-Datasets#55]
LightVisibilty = obscured (7) is not allowed for a LightSectored.

Taking account the situation (see image above) and the instructions from dceg , 
"If there is no navigable water between the light and the obstacle (see (e) in Figure 19.2 (B) above), the masked sector must not have an iteration of light sector encoded, ...."

I propose not to encode this sector light.

![LightVisiblityObscured](https://github.com/iho-ohi/S-101-Test-Datasets/assets/24851994/c31b7c26-4995-4ac9-939d-cc480fbb1b6e)

**Comment by TomRichardson6** [comment]
Issue fixed in Edtn 2 of this cell.
