### ISSUE TITLE
Quality of Bathymetric Data and ECDIS Performance (Management of Temporal variation)

### ISSUE THREAD

**Issue by alvarosanuy** [iho-ohi/S-101-Test-Datasets#57]
Request S-101 test dataset to check the temporal degradation of **QoBD** when multiple **zoneOfConfidence** complex attributes are encoded and triggered by sequential combinations of **fixedDateRange**.

#### Input QoBD zoneOfConfidence attributes and resulting portrayal
|categoryOfZoneOfConfidenceInData|fixedDateRange.dateStart|fixedDateRange.dateEnd|
|:---:|:---:|:---:|
|1||20211231|
|3|20220101|20221231|
|5|20230101||

|Selected Viewing Date|Portrayal (click to enlarge)|Remarks|
|:---:|:---:|:---|
|Jan 1, 2010|![ShoreECDIS 2022-10-20T202651Z](https://user-images.githubusercontent.com/62906211/197051536-fd6ce42c-d815-48f8-9b64-9bfa1e8e5338.png)|Applies to any date prior to 2022|
|Oct 20, 2022|![ShoreECDIS 2022-10-20T202702Z](https://user-images.githubusercontent.com/62906211/197051719-920ef6ee-c000-4d34-85fc-ff16cef20756.png)|Applies to any date in 2022|
|Jan 1, 2025|![ShoreECDIS 2022-10-20T202716Z](https://user-images.githubusercontent.com/62906211/197051838-aa129b5f-02f6-429f-aa6f-98bc9b101aa2.png)|Applies to any date after 2022

**Comment by plebihan29n** [comment]
Alvaro,Tom

In the new version S-164_1.1/V2/ , I have generated "temporal variation" on this quality of bathymetric area (see my image below)
![for57](https://github.com/iho-ohi/S-101-Test-Datasets/assets/24851994/ecddc3af-e20b-4d63-a12b-27710c7e896e)

This proposal concerns 00AA_X0000, 00AA_X01NW,  00AA_X01SW datasets and have to be considered as an exercise. If the result is conform ,we will see if there is an another more appropriate to support this "temporal variation".

Pol

**Comment by plebihan29n** [comment]
Just for information, I have change the original S-57 CATZOC quality of this M_QUAL object to A1, and in the conversion to S101, I have degrade it with the time as require.

**Comment by DavidGrant-NIWC** [comment]
Looks good, recommend close this issue.

![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/62906211/a1f4c679-4afd-4c8e-92f1-52e3ed9cf24b)

**Comment by alvarosanuy** [comment]
Great, thanks! Happy for this issue to be closed.
