### ISSUE TITLE
S-164_1.1/V2/3.1 ENC Display/Standard : NoticeToMariner

### ISSUE THREAD

**Issue by plebihan29n** [iho-ohi/S-101-Test-Datasets#59]
1- The two instances of S-57 NEWOBJ (Generic Object) of this "standard display" S-57 dataset, have been encoded to portray "Temporary and Primary Notice To Mariner" and has not been converted in S-101 taking account the fact that only NEWOBJ with CLSNAM starts with "Virtual AtoN" instances are converted to S101 feature type VirtualAISAidToNavigation.

2- A specific conversion could be done to convert  the NEWOBJ area feature to S101 feature type "AnchorageArea" and the NEWOBJ curve feature  to S101 feature type "Dam" , and for both  adequate "fixedDataRange" attributes and information/name attributes to set the origin "P-Notice To Mariner" or "T-Notice To Mariner"

3- The reason is that "AnchorageArea" and "Dam"  are feature types concerned by the "S-101 standard display viewing group layers" and support "fixedDataRange" attributes.

Question : Are you support this specific conversion ? == (Not sure this is the good place to illustrate NoticeToMariner.) Improving the isolated updates examples in "2.2 loading of updates" could be better .

**Comment by plebihan29n** [comment]
This proposal has been encoded the delivered version 3 of S-164

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/62906211/ed8d072b-b1fa-4ed9-b4b6-2ea8a7d33dc1)

**Comment by TomRichardson6** [comment]
Thank you @plebihan29n I think this is a logical change and I will now close this issue.
