### ISSUE TITLE
S-164_1.1/V2/3.1 ENC Display/Base : Bridge Point

### ISSUE THREAD

**Issue by plebihan29n** [iho-ohi/S-101-Test-Datasets#61]
A bridge with a point geometry has been encoded in the S57 test dataset "AA5DBASE".
The choice of our converter is to encode it as a S-101 LandMark Feature. (due to the fact that  Point SpanFixed Feature  is  not allowed by the S-101 specification).
In consequence this "LandMark feature" doesn't belong to S-101 Display base.
Proposal : Transfert this feature to the "Other" test dataset ?
![DisplayBase](https://github.com/iho-ohi/S-101-Test-Datasets/assets/24851994/6fd6ec8a-666c-4d31-bcfe-01c22113587b)

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/62906211/d98e3cb9-d294-4865-8ed0-1738f36e3588)
