### ISSUE TITLE
 S-164_1.1/V2/GroupOne : Lock Basin and Dock Area

### ISSUE THREAD

**Issue by plebihan29n** [iho-ohi/S-101-Test-Datasets#62]
Error in V2 : Lock Basin and Dock Area instances have been encoded as objects that belong to the group one.

**Comment by plebihan29n** [comment]
This issue has been corrected in the delivered version 3 of S-164

**Comment by DavidGrant-NIWC** [comment]
|`Base`|`Standard`|
|:---:|:---:|
|![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/62906211/e1534f08-608f-45a4-8ad7-fbe33c4e5b26)|![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/62906211/100f1b3f-4b8e-48e4-a269-51bb12ecfa85)|
