### ISSUE TITLE
S-164_1.1/V2/3.1 ENC Display/Dock Area&Lock Basin to Standard DataSet

### ISSUE THREAD

**Issue by plebihan29n** [iho-ohi/S-101-Test-Datasets#63]
The "Dock Area" and "Lock Basin" instances have been encoded in the S57 "AA5DBASE" conform to the fact in S-57 ENC specification theses instances belong to the group one objects and display mode "base".

In S-101 specification The "Dock Area" and "Lock Basin" don't belong to the group one and in turn don't belong to the display base category in portrayal S-101.

Proposal : Transfer these instances to the S-101 Standard Test Data-Set "S10100AA_STNDR"

**Comment by DavidGrant-NIWC** [comment]
Agree, and fix the "holes" underneath these features:
![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/62906211/85261ccc-028c-40db-a0be-852c5cd527f4)

![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/62906211/28a4b257-f6f6-42f4-8fcf-0c8cf64b44e2)

**Comment by plebihan29n** [comment]
Noted.  "fix the "holes" underneath these features" will be done under the issue #62

**Comment by plebihan29n** [comment]
This proposal has been encoded in the delivered version 3 of S-164

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/62906211/9c04a6fc-ba83-4607-afda-b48287e30715)
