### ISSUE TITLE
Local Direction of Buoyage should have same MARSYS as underlying Navigational System of Marks

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Test-Datasets#66]
![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/62906211/7fc87939-de89-44e5-b11a-bacbde19a0bf)

![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/62906211/98c59685-ec14-4bf0-8024-618502c57464)

**Comment by plebihan29n** [comment]
OK noted for the next version (V3)

**Comment by plebihan29n** [comment]
This issue has been corrected in the delivered version 3 of S-164
