### ISSUE TITLE
 S-164_1.1/V3/3.6 Display Priorities/NEWOBJ 

### ISSUE THREAD

**Issue by plebihan29n** [iho-ohi/S-101-Test-Datasets#67]
This issue is link to a more global issue "How to convert S-64-S-57 Generic New-Objects ?"

For the specific cases of the test dataset "1012J5X0001" , here are my proposals :

- To delimit part of the datasets , I use a "floating depth contour" (150m)
- To support "point information" , I use "SeaAreaNameWater"
- To support "unknown objects" , I use "TideHarmonicPrediction" (unknown for the S-101 FC but known from S-100 Register)
- To support "Manual Updates", I use "Update Information" => but it seems not the good choice , if you have any ideas => the objectif is to portray "delete,modify,insert" update symbologies.

![NewObjects](https://github.com/iho-ohi/S-101-Test-Datasets/assets/24851994/930b94e8-128b-424d-b1c9-7995ddf81af4)

**Comment by plebihan29n** [comment]
This proposal has been encoded in the delivered version 3 of S-164

**Comment by TomRichardson6** [comment]
Solution is considered acceptable at this stage. Further review as part of S-164 development.
