### ISSUE TITLE
S-164_1.1 V2 2.2.2 Loading of Updates - invalid exchange catalog

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Test-Datasets#68]
Main issue is that dataset updates are not support files, they are datasets and therefore should have DatasetDiscoveryMetadata rather than SupportFileDiscoveryMetadata.

![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/62906211/05adc79d-b503-4abf-acc3-7b144a60890c)

Also note that <S100XC:dataType> doesn't conform to the schema.

![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/62906211/2a2ddac6-34e4-4456-aa1a-86ebeb0183f5)
![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/62906211/87f5e685-c66d-44f0-8b48-56c5918e955d)

**Comment by plebihan29n** [comment]
OK noted for the next version (V3)

**Comment by plebihan29n** [comment]
Corrected in the current version.
