### ISSUE TITLE
S-164_1.1 V2 2.2.4 Loading of New Update

### ISSUE THREAD

**Issue by plebihan29n** [iho-ohi/S-101-Test-Datasets#70]
In the S-164 "Loading of New Update" , to update a curve (delete points and insert new points) , The following sequence has been generated in the **same record** :

![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/24851994/e3697e2e-19c3-4894-8927-55e86da04531)

This sequence is not conform as the "COCC" field is use twice in the same record.

![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/24851994/a2356be7-2753-4853-85e1-2efc90b9062d)

Taking account the multiplicity of COCC (one field max) this sequence has to be generated in two **separate records** (one for deletion, one for insertion).

Another solution (more efficient) is to use only one update record by  insert only new points of this curve.

**Comment by plebihan29n** [comment]
Here is the sequence (delete + insert all coordinates) that has been encoded :
![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/24851994/d6cfe30e-112b-4d41-8a50-c3fac59c65f3)


A further version could be encoded using the modify sequence that will consist to insert new coordinates.

**Comment by TomRichardson6** [comment]
I am happy that edition 3 has addressed this Issue closed.
