### ISSUE TITLE
S-164 TestDataSets 2.1.1 Power Up support file content doesn't match file name

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Test-Datasets#73]
10100AACHAINS.TXT: "This is a test file called GBCHAINS.TXT"
10100AADEVARE.TXT: "This is a test file called GBDEVARE.TXT"

**Comment by plebihan29n** [comment]
The content of pointed files has been modified for consistency with the name of the file.

**Comment by DavidGrant-NIWC** [comment]
![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/62906211/f0d5f77f-bde4-45bd-a22d-526cbd537129)

![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/62906211/480486c2-d956-4e1d-a151-3c0e5d12f9b4)
