### ISSUE TITLE
Preferred Channels missing colour attribute encodings

### ISSUE THREAD

**Issue by mikan66** [iho-ohi/S-101-Test-Datasets#75]
Only single colors are encoded. 
![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/4913543/e0996315-bbc2-46b9-b8bc-3d5e6f3d777a)

Reference Dataset: 
![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/4913543/1377912b-a41e-483a-85b8-942b149b3f74)

Refer to DCEG Table 18.1, (approximate page 409, Edition 1.1.0 March 2023), for example of preferred channel colour encoding.  The test dataset only encodes 1 color instead of 3 colors.

![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/4913543/b55853d5-204a-4986-bb26-aa634bfa87fb)
 
![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/4913543/d576db00-e2e1-442e-ade7-e222012efd21)

**Comment by TomRichardson6** [comment]
@mikan66 the two features in the screenshot provided are port hand lateral marks. I have reviewed the 8 preferred channel marks which sit at the bottom of the islands within the two fairways and have confirmed that all features have multiple colours encoded.
