### ISSUE TITLE
Virtual Aids to Navigation in 10100AA_OVRVU

### ISSUE THREAD

**Issue by kusala9** [iho-ohi/S-101-Test-Datasets#79]
I was doing a side by side comparison of the S-57 and S-101 AA2OVRVU for inclusion in S-164 and noticed one of the Virtual AtoN in the S-101 has type unknown. 

these are the encodings (S-57 vs S-101)

![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/3368156/98c72b45-ca01-4309-9c34-39ab6a1a9f46)

I believe it should be type Emergency Wreck Marking Buoy. 

Also, I don't believe we need to retain the INFORM values as Nautical Information types - they can be deleted as all the information is contained in the feature....

**Comment by TomRichardson6** [comment]
The cell has been updated and published this issue has been resolved.
