### ISSUE TITLE
min/max scales are reversed for DS7 and 15

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Test-Datasets#8]
101AA00DS006.000 and 101AA00DS007.000 have the min and max scales reversed: min=22k and max=90k

**Comment by DavidGrant-NIWC** [comment]
and DS15

**Comment by DavidGrant-NIWC** [comment]
Updated issue title - DS6 is fixed, Issue remains in DS7 and 15

**Comment by TomRichardson6** [comment]
DS7 and DS5 have now been updated to address this issue.
