### ISSUE TITLE
101AA005C1Q02.000 missing DataCoverage

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Test-Datasets#82]
The area of the channel does not have a Data Coverage feature

![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/62906211/c72f0910-45e8-4ba5-8544-1b34099192c1)

**Comment by kusala9** [comment]
ah, Data Coverage was attached to the wrong Surface. Now corrected and in repository.
