### ISSUE TITLE
DS0001 ed6: feature 8 iku name has incorrect encoding

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Test-Datasets#87]
Feature 8 has an incorrect UTF-8 encoding for the iku name: 
![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/62906211/830de850-4ee9-48a6-af2a-4152f9d46934)

**Comment by kusala9** [comment]
looks like a UTF-8 issue. I will check.

**Comment by DavidGrant-NIWC** [comment]
Can be verified in the pick report. Our text rendering code has an issue with non-ascii strings in the version you are using. It'll be corrected in the next update.

**Comment by kusala9** [comment]
Value: ???ᔭ???????ᔪ???ᑦ
that'll be why. I don't have the UTF-8 version of the name.

**Comment by kusala9** [comment]
I've just pushed edition 7, should fix the issue. including the default/alternative values.

**Comment by DavidGrant-NIWC** [comment]
Fixed.
![image](https://github.com/iho-ohi/S-101-Test-Datasets/assets/62906211/bc7a7119-782c-4972-8a4d-43f7388b84df)
